#! /bin/bash

grep_port () {
    echo "Activiating ports:"
    grep -A8 $1 docker-compose.yml | grep -A2 ports | grep "-"
}

setup () {
    # echo "${@}"
    ./setup.sh $@
}

clean () {
    # Move log files to the logs/archive directory to work with a clean log file. 
    # When the log file is moved a prefix of the date is added. 

    echo "Archiving log files from the logs/ dir"
    
    move_file () {
        if [ -f ${1}${2} ]; then
            echo "Archiving log file ${1}${2} to ${3}${4}${2}"
            mv ${1}${2} ${3}${4}${2};
        fi

    }

    remove_file () {
        PAUSETIMER=5
        if [ -f ${1} ]; then
            echo ''
            echo "About to delete file '${1}'. Pausing for ${PAUSETIMER} to silently confirm consent."
            sleep ${PAUSETIMER}
            rm -f ${1}
        fi
        echo 'Delete successful, continuing'
    }

    DATE=$(date '+%Y%m%d%H%M%S')
    move_file "logs/" "weatherman.log" "logs/archive/" "${DATE}_"
    move_file "logs/" "weatherman_startup.log" "logs/archive/" "${DATE}_"
    move_file "logs/" "weatherman_dev.log" "logs/archive/" "${DATE}_"

    remove_file "etc/city_list.gz"

    echo "Done!"
}

run () {
    # Use docker-compose to spin up the app. 
    grep_port "weather"
    docker-compose up -d weather
}

dev () {
    # Spin up the dev environment. 
    grep_port "dev"
    docker-compose up dev
}

stop () {
    # Stop weatherman containers

    echo "Stopping all weatherman containers"

    docker stop $(docker ps --filter name=weatherman* -aq)
}

clense () {
    # Find all containers that have weatherman* in the name and stop/rm them. 

    echo "About to stop/rm all weatherman containers. If one is running in terminal this cmd will wait"

    docker stop $(docker ps --filter name=weatherman* -aq)
    docker rm $(docker ps --filter name=weatherman* -aq)
    # docker ps --filter name=weatherman* -aq | xargs docker stop | xargs docker rm
}


unit () {
    # Run the unit tests. 
    # This includes flake and lenting
    docker-compose run --rm unit-test
}

functional () {
    # Run the functional tests. 
    docker-compose run --rm test
}

tests () {
    # Run each test. 
    # I have them seporated in case i want to grep for things in the test or save them to files. 
    unit
    functional
}

about () {
    echo "
    This is a makeshift Makefile
    setup               - Set up dir and files (run if its a new cloan)
                            For more info run 'build setup help'
                            For a full program setup run 'build setup reset-all'
    clean               - Move log files to the logs/archive directory
    run                 - Run the container
    dev                 - Run a dev instance
    clean-run           - Clean then run
    clean-dev           - Clean then dev
    stop                - Stop weatherman containers
    clense-containers   - Stop/rm weatherman containers
    unit                - Unit tests
    functional          - Functional tests
    tests               - Unit then Functional
    help                - Uhhh speaking...
    "
}

case "$1" in
    # Setup
    setup)
        setup "${@}"
        ;;

    clean)
        clean
        ;;

    # Running
    run)
        run
        ;;
    dev)
        dev
        ;;
    clean-run)
        clean
        run
        ;;
    clean-dev)
        clean
        dev
        ;;

    # Stopping
    stop)
        stop
        ;;
    clense-containers)
        clense
        ;;

    # Testing
    unit)
        unit
        ;;
    functional)
        functional
        ;;
    tests)
        tests
        ;;

    # Help
    help)
        about
        ;;

    *)
        about
        ;;
esac
