version: '3'

services:

    weather:
        build: .
        image: weather:latest
        restart: always
        command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8000:8000

        environment:
            - ENVIRONMENT=prod
            - TESTING=False
            - AUTOPOLLING=True

    dev:
        build: .
        image: weather-dev:latest
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8010:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=False
            - AUTOPOLLING=False

    functional:
        build: .
        image: weather-functional:latest
        # command: behave features/data_validator.feature
        # command: behave features/main.feature:6
        # command: behave --tags="@owma"
        command: behave
        volumes:
            - .:/usr/src
        ports:
            - 8020:8000
        environment:
            - ENVIRONMENT=test
            - TESTING=True
            - AUTOPOLLING=False

    unit:
        build: .
        image: weather-unit:latest
        command: pytest --cov=. .
        # command: pytest --cov=. tests/test_data_validator.py
        # command: pytest --cov=. tests/test_application.py
        volumes:
            - .:/usr/src
        ports:
            - 8021:8000
        environment:
            - ENVIRONMENT=test
            - TESTING=True
            - AUTOPOLLING=False

    lint:
        build: .
        image: weather-lint:latest
        command: pycodestyle --show-source
        # command: pycodestyle dev_tools/main_tool.py --show-source
        # command: pycodestyle dev_tools/main_tool.py --show-source --show-pep8
        volumes:
            - .:/usr/src
        ports:
            - 8022:8000
        environment:
            - ENVIRONMENT=test
            - TESTING=True
            - AUTOPOLLING=False
